# Pandas 入门：Series 与 DataFrame，认识数据表的两种形态

> 这是「数据分析从入门到精通」系列的第 7 篇，也是 Pandas 阶段的开篇。NumPy 打好了地基，现在来盖房子——真实的数据分析工作，80% 的时间都在这里。

---

嗨，我是小荷。

NumPy 六篇走完，恭喜你把数组操作和矩阵运算搞定了。但说实话，平时工作里你拿到的数据长这样：

| 订单ID | 用户名 | 商品 | 金额 | 下单时间 |
|--------|--------|------|------|----------|
| 1001 | 张三 | 耳机 | 299 | 2024-01-03 |
| 1002 | 李四 | 键盘 | 459 | 2024-01-03 |

这种**有行有列、有列名、有混合类型**的表格数据，NumPy 处理起来并不顺手。**Pandas 就是为此而生的**。

萧何当年管账，不可能每笔账都是纯数字——粮草有名称、有数量、有日期、有来源地……这种"结构化账簿"，就是今天我们要聊的 DataFrame。

---

## Pandas 是什么？

Pandas 是基于 NumPy 的数据分析库，提供两种核心数据结构：

- **Series**：一维带标签的数组（像一列数据）
- **DataFrame**：二维带标签的表格（像一张 Excel 表）

In [1]:
import pandas as pd
import numpy as np

---

## Series：一列数据

### 创建 Series

In [2]:
# 从列表创建
scores = pd.Series([85, 92, 78, 96, 88])
print(scores)
# 0    85
# 1    92
# 2    78
# 3    96
# 4    88
# dtype: int64

# 自定义索引
scores = pd.Series(
    [85, 92, 78, 96, 88],
    index=['张三', '李四', '王五', '赵六', '小荷']
)
print(scores['小荷'])  # 88

0    85
1    92
2    78
3    96
4    88
dtype: int64
88

### Series 的核心属性

In [3]:
print(scores.index)    # 索引
print(scores.values)   # 值（NumPy 数组）
print(scores.dtype)    # 数据类型
print(scores.shape)    # 形状，如 (5,)
print(len(scores))     # 长度

Index(['张三', '李四', '王五', '赵六', '小荷'], dtype='str')
[85 92 78 96 88]
int64
(5,)
5

### Series 的常用操作

In [4]:
# 支持向量化运算（广播机制）
print(scores + 5)       # 所有成绩加5分
print(scores[scores > 90])  # 筛选大于90的

# 统计方法
print(scores.mean())    # 均值
print(scores.max())     # 最大值
print(scores.describe()) # 一键出描述统计

张三     90
李四     97
王五     83
赵六    101
小荷     93
dtype: int64
李四    92
赵六    96
dtype: int64
87.8
96
count     5.000000
mean     87.800000
std       6.870226
min      78.000000
25%      85.000000
50%      88.000000
75%      92.000000
max      96.000000
dtype: float64

> Series 本质上是「有名字的 NumPy 数组」，所有 NumPy 的向量化操作在 Series 上都能用。

---

## DataFrame：二维数据表

### 创建 DataFrame

In [5]:
# 从字典创建（最常用）
data = {
    '姓名': ['张三', '李四', '王五', '赵六'],
    '语文': [85, 92, 78, 96],
    '数学': [90, 68, 87, 75],
    '英语': [88, 95, 82, 91]
}
df = pd.DataFrame(data)
print(df)
#    姓名  语文  数学  英语
# 0  张三   85   90   88
# 1  李四   92   68   95
# 2  王五   78   87   82
# 3  赵六   96   75   91

# 从 NumPy 数组创建
arr = np.random.randint(60, 100, size=(4, 3))
df2 = pd.DataFrame(arr, columns=['语文', '数学', '英语'])

   姓名  语文  数学  英语
0  张三  85  90  88
1  李四  92  68  95
2  王五  78  87  82
3  赵六  96  75  91

### DataFrame 的核心属性

In [6]:
print(df.shape)        # (4, 4) — 行数和列数
print(df.columns)      # 列名
print(df.index)        # 行索引
print(df.dtypes)       # 每列的数据类型
print(df.values)       # 转为 NumPy 数组

(4, 4)
Index(['姓名', '语文', '数学', '英语'], dtype='str')
RangeIndex(start=0, stop=4, step=1)
姓名      str
语文    int64
数学    int64
英语    int64
dtype: object
[['张三' 85 90 88]
 ['李四' 92 68 95]
 ['王五' 78 87 82]
 ['赵六' 96 75 91]]

---

## DataFrame 的基础操作

### 查看数据

In [7]:
df.head(3)      # 前3行
df.tail(2)      # 后2行
df.info()       # 数据概览（行数、列数、数据类型、内存）
df.describe()   # 数值列的描述统计（均值、标准差、分位数等）

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   姓名      4 non-null      str
 1   语文      4 non-null      int64
 2   数学      4 non-null      int64
 3   英语      4 non-null      int64
dtypes: int64(3), str(1)
memory usage: 260.0 bytes

              语文        数学         英语
count   4.000000   4.00000   4.000000
mean   87.750000  80.00000  89.000000
std     7.932003  10.29563   5.477226
min    78.000000  68.00000  82.000000
25%    83.250000  73.25000  86.500000
50%    88.500000  81.00000  89.500000
75%    93.000000  87.75000  92.000000
max    96.000000  90.00000  95.000000

`df.info()` 的输出长这样：
```
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   姓名      4 non-null      object
 1   语文      4 non-null      int64
 2   数学      4 non-null      int64
 3   英语      4 non-null      int64
dtypes: int64(3), object(1)
memory usage: 260.0+ bytes
```

> 拿到新数据集，先跑 `df.info()` 和 `df.describe()`，这是最快的"数据体检"方式。

### 取列

In [8]:
# 取单列（返回 Series）
df['语文']
df.语文       # 属性访问，列名是合法变量名时可以用

# 取多列（返回 DataFrame）
df[['语文', '数学']]

   语文  数学
0  85  90
1  92  68
2  78  87
3  96  75

### 取行

In [9]:
# 按索引取行
df.iloc[0]      # 第0行（位置索引）
df.iloc[1:3]    # 第1到第2行

# 按标签取行
df.loc[0]       # 索引为0的行

姓名    张三
语文    85
数学    90
英语    88
Name: 0, dtype: object

### 新增和修改列

In [11]:
# 新增总分列
df['总分'] = df['语文'] + df['数学'] + df['英语']

# 新增等级列
df['等级'] = df['总分'].apply(lambda x: 'A' if x >= 270 else 'B')

print(df)
#    姓名  语文  数学  英语   总分 等级
# 0  张三   85   90   88  263   B
# 1  李四   92   68   95  255   B
# 2  王五   78   87   82  247   B
# 3  赵六   96   75   91  262   B

   姓名  语文  数学  英语   总分 等级
0  张三  85  90  88  263  B
1  李四  92  68  95  255  B
2  王五  78  87  82  247  B
3  赵六  96  75  91  262  B

---

## Series vs DataFrame 的关系

```
DataFrame = 多个 Series 拼在一起

df['语文']  →  返回一个 Series
df[['语文', '数学']]  →  返回一个 DataFrame
```

可以这样理解：**DataFrame 是账本，Series 是账本里的某一列**。萧何的账本上有日期列、物资列、数量列，每一列单独拿出来就是一个 Series。

---

## 实战：快速了解一份陌生数据集

In [12]:
import pandas as pd
import numpy as np

# 模拟一份电商订单数据
np.random.seed(42)
n = 100
df = pd.DataFrame({
    '订单ID': range(1001, 1001 + n),
    '用户ID': np.random.randint(1, 20, n),
    '商品类别': np.random.choice(['数码', '服装', '食品', '图书'], n),
    '金额': np.random.uniform(10, 1000, n).round(2),
    '数量': np.random.randint(1, 5, n),
    '是否退款': np.random.choice([True, False], n, p=[0.1, 0.9])
})

# === 数据体检五步走 ===
print("【1】基本信息")
print(f"  行数: {df.shape[0]}, 列数: {df.shape[1]}")

print("\n【2】数据类型")
print(df.dtypes)

print("\n【3】前5行")
print(df.head())

print("\n【4】数值统计")
print(df.describe().round(2))

print("\n【5】缺失值检查")
print(df.isnull().sum())

【1】基本信息
  行数: 100, 列数: 6

【2】数据类型
订单ID      int64
用户ID      int64
商品类别        str
金额      float64
数量        int64
是否退款       bool
dtype: object

【3】前5行
   订单ID  用户ID 商品类别      金额  数量   是否退款
0  1001     7   服装  409.80   4  False
1  1002    15   食品   74.24   1  False
2  1003    11   食品  261.38   4  False
3  1004     8   数码  254.41   1  False
4  1005     7   食品  699.34   4   True

【4】数值统计
          订单ID    用户ID      金额      数量
count   100.00  100.00  100.00  100.00
mean   1050.50    9.64  552.11    2.52
std      29.01    5.30  271.28    1.12
min    1001.00    1.00   27.89    1.00
25%    1025.75    5.00  328.27    2.00
50%    1050.50    9.00  540.83    2.50
75%    1075.25   14.00  790.71    4.00
max    1100.00   19.00  997.76    4.00

【5】缺失值检查
订单ID    0
用户ID    0
商品类别    0
金额      0
数量      0
是否退款    0
dtype: int64

这五步，是我每次拿到新数据集必跑的操作，养成习惯，省很多后续的排查时间。

---

## 本篇小结

| 对象 | 维度 | 特点 | 类比 |
|------|------|------|------|
| Series | 一维 | 带标签的数组 | 账本里的一列 |
| DataFrame | 二维 | 带行列标签的表格 | 完整的账本 |

**记住三件事：**
1. `df.info()` + `df.describe()` 是拿到数据必跑的第一步
2. 取单列用 `df['列名']`（返回 Series），取多列用 `df[['列名1','列名2']]`（返回 DataFrame）
3. Series 和 NumPy 数组很像，NumPy 能做的操作 Series 基本都能做

---

## 课后练习

In [15]:
import pandas as pd

data = {
    '城市': ['北京', '上海', '广州', '深圳', '杭州'],
    'GDP(亿元)': [41610, 43214, 28839, 32387, 20035],
    '人口(万人)': [2184, 2489, 1882, 1766, 1237],
    '一线城市': [True, True, False, False, False]
}
df = pd.DataFrame(data)

# 任务1：打印 df 的基本信息（行列数、类型）
# 任务2：计算每个城市的人均 GDP（单位：万元/人），新增一列
# 任务3：筛选出 GDP 超过 3 万亿的城市
# 任务4：找出人口最多的城市名称

In [16]:
# 任务1：打印 df 的基本信息（行列数、类型）
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   城市       5 non-null      str
 1   GDP(亿元)  5 non-null      int64
 2   人口(万人)   5 non-null      int64
 3   一线城市     5 non-null      bool
dtypes: bool(1), int64(2), str(1)
memory usage: 257.0 bytes

In [19]:
# 任务2：计算每个城市的人均 GDP（单位：万元/人），新增一列
df['人均GDP(万元/人)'] = df['GDP(亿元)']/df['人口(万人)']
df

   城市  GDP(亿元)  人口(万人)   一线城市     人均 GDP  人均GDP(万元/人)
0  北京    41610    2184   True  19.052198    19.052198
1  上海    43214    2489   True  17.361993    17.361993
2  广州    28839    1882  False  15.323592    15.323592
3  深圳    32387    1766  False  18.339185    18.339185
4  杭州    20035    1237  False  16.196443    16.196443

In [20]:
# 任务3：筛选出 GDP 超过 3 万亿的城市
df[df['GDP(亿元)'] > 30000]

   城市  GDP(亿元)  人口(万人)   一线城市     人均 GDP  人均GDP(万元/人)
0  北京    41610    2184   True  19.052198    19.052198
1  上海    43214    2489   True  17.361993    17.361993
3  深圳    32387    1766  False  18.339185    18.339185

In [27]:
# 任务4：找出人口最多的城市名称
max_index = df['人口(万人)'].idxmax()
df.loc[max_index, '城市']

'上海'

评论区见 👀

本篇完整代码包括练习题解答都已经上传至 GitHub 仓库，欢迎 Clone。

---

## 下期预告

> **第 8 篇：数据读取 — CSV / Excel / JSON / SQL**
>
> 学会 DataFrame 的基本操作之后，下篇来解决"数据从哪来"的问题——手把手带你读取各种格式的真实数据文件，还有几个超级实用的读取技巧。

---

**Pandas 开篇，感觉跟 NumPy 差别大吗？**

👇 点「在看」推给更多想学 Pandas 的人  
💬 评论区聊聊你平时用什么工具处理表格数据  
⭐ 关注公众号，跟萧何迷妹一起搞定真实数据

---

*「数据分析从入门到精通」系列 · 第 7 篇*  
*上一篇：[第 6 篇：随机数与矩阵运算]*  
*下一篇：第 8 篇：数据读取 — CSV / Excel / JSON / SQL*