# 行列筛选：loc / iloc / 条件查询，精准提取目标数据

> 这是「数据分析从入门到精通」系列的第 10 篇。数据读进来、也看明白了，这篇解决"精准取数"的问题——彻底搞懂 loc 和 iloc 的区别，掌握条件查询的所有姿势。

---

嗨，我是小荷。

上一篇我们学会了"看数据"，这一篇学"取数据"。

你可能会问：NumPy 那边不是已经学过索引和切片了吗？Pandas 有什么不一样？

有一个核心区别：**NumPy 只有位置索引（数字），Pandas 有标签索引（列名/行名）**。这让 Pandas 的取数方式更灵活，但也更容易搞混。

萧何管账，可以按"第几本"翻账簿（位置），也可以按"哪个郡"找记录（标签）。Pandas 的 loc 和 iloc，就是这两种方式的具体实现。

---

## iloc：按位置取（I = Integer）

`iloc` 永远按**整数位置**取数，用法和 NumPy 二维数组完全一样。

In [2]:
import pandas as pd

df = pd.read_csv('全国城市数据.csv', encoding = 'gbk')

# 取单行（返回 Series）
df.iloc[0]         # 第0行

省份                   内蒙古自治区
城市名称                  呼伦贝尔市
城市级别                     二线
常住人口(万人)                248
面积(km2)              252777
人均面积(km2/万人)    1019.262097
火星纬度(GCJ02)         49.2126
火星经度(GCJ02)        119.7654
Name: 0, dtype: object

In [3]:
df.iloc[-1]        # 最后一行

省份                   广东省
城市名称                 东莞市
城市级别                 准一线
常住人口(万人)            1046
面积(km2)             2462
人均面积(km2/万人)    2.353728
火星纬度(GCJ02)      23.0207
火星经度(GCJ02)     113.7518
Name: 342, dtype: object

In [4]:
# 取多行（返回 DataFrame）
df.iloc[0:5]       # 前5行

,省份,城市名称,城市级别,常住人口(万人),面积(km2),人均面积(km2/万人),火星纬度(GCJ02),火星经度(GCJ02)
0,内蒙古自治区,呼伦贝尔市,二线,248,252777,1019.262097,49.2126,119.7654
1,内蒙古自治区,鄂尔多斯市,二线,215,86752,403.497674,39.6081,110.0235
2,内蒙古自治区,赤峰市,二线,430,90021,209.351163,42.2566,118.9220
3,内蒙古自治区,通辽市,二线,312,59535,190.817308,43.6529,122.2440
4,四川省,凉山彝族自治州,二线,484,60423,124.840909,27.8868,102.2674

In [5]:
df.iloc[[0, 2, 4]] # 第0、2、4行

,省份,城市名称,城市级别,常住人口(万人),面积(km2),人均面积(km2/万人),火星纬度(GCJ02),火星经度(GCJ02)
0,内蒙古自治区,呼伦贝尔市,二线,248,252777,1019.262097,49.2126,119.7654
2,内蒙古自治区,赤峰市,二线,430,90021,209.351163,42.2566,118.9220
4,四川省,凉山彝族自治州,二线,484,60423,124.840909,27.8868,102.2674

In [6]:
# 取单个值
df.iloc[0, 1]      # 第0行，第1列

'呼伦贝尔市'

In [7]:
# 取行列区间
df.iloc[0:3, 0:3]  # 前3行，前3列

       省份   城市名称 城市级别
0  内蒙古自治区  呼伦贝尔市   二线
1  内蒙古自治区  鄂尔多斯市   二线
2  内蒙古自治区    赤峰市   二线

In [8]:
df.iloc[:, 2]      # 所有行，第2列

0       二线
1       二线
2       二线
3       二线
4       二线
      ...
338    准一线
339    准一线
340    准一线
341    准一线
342    准一线
Name: 城市级别, Length: 343, dtype: str

---

## loc：按标签取（L = Label）

`loc` 按**行标签**和**列名**取数，更符合"按名字找数据"的直觉。

In [9]:
# 按列名取列（最常用！）
df.loc[:, '城市名称']               # 等价于 df['城市名称']

0        呼伦贝尔市
1        鄂尔多斯市
2          赤峰市
3          通辽市
4      凉山彝族自治州
        ...
338        无锡市
339        郑州市
340        佛山市
341        厦门市
342        东莞市
Name: 城市名称, Length: 343, dtype: str

In [10]:
df.loc[:, ['省份', '城市名称', '城市级别']]  # 取多列

         省份     城市名称 城市级别
0    内蒙古自治区    呼伦贝尔市   二线
1    内蒙古自治区    鄂尔多斯市   二线
2    内蒙古自治区      赤峰市   二线
3    内蒙古自治区      通辽市   二线
4       四川省  凉山彝族自治州   二线
..      ...      ...  ...
338     江苏省      无锡市  准一线
339     河南省      郑州市  准一线
340     广东省      佛山市  准一线
341     福建省      厦门市  准一线
342     广东省      东莞市  准一线

[343 rows x 3 columns]

In [12]:
# 按行索引取行
df.loc[0]          # 行索引为 0 的行

省份                   内蒙古自治区
城市名称                  呼伦贝尔市
城市级别                     二线
常住人口(万人)                248
面积(km2)              252777
人均面积(km2/万人)    1019.262097
火星纬度(GCJ02)         49.2126
火星经度(GCJ02)        119.7654
Name: 0, dtype: object

In [13]:
df.loc[0:4]        # 注意：loc 的切片是闭区间，包含第4行！

,省份,城市名称,城市级别,常住人口(万人),面积(km2),人均面积(km2/万人),火星纬度(GCJ02),火星经度(GCJ02)
0,内蒙古自治区,呼伦贝尔市,二线,248,252777,1019.262097,49.2126,119.7654
1,内蒙古自治区,鄂尔多斯市,二线,215,86752,403.497674,39.6081,110.0235
2,内蒙古自治区,赤峰市,二线,430,90021,209.351163,42.2566,118.9220
3,内蒙古自治区,通辽市,二线,312,59535,190.817308,43.6529,122.2440
4,四川省,凉山彝族自治州,二线,484,60423,124.840909,27.8868,102.2674

In [14]:
# 取单个值
df.loc[0, '城市名称']    # 第0行，城市名称列

'呼伦贝尔市'

> ⚠️ **iloc vs loc 的切片区别**：
> - `iloc[0:5]` → 取第 0、1、2、3、4 行（**不含**第5行，像 Python）
> - `loc[0:5]` → 取索引 0、1、2、3、4、5 的行（**含**第5行）
>
> 这个区别坑过无数人，记清楚。

---

## 条件查询：筛选满足条件的行

这才是 Pandas 筛选数据最常用的方式，逻辑和 NumPy 的布尔索引完全一样。

### 单条件筛选

In [16]:
# 筛选一线城市
first_tier = df[df['城市级别'] == '一线']
print(first_tier[['省份', '城市名称']])

# 筛选人口超过1000万的城市
big_cities = df[df['常住人口(万人)'] > 1000]

# 筛选面积小于5000的城市
small_area = df[df['面积(km2)'] < 5000]

      省份 城市名称
302  北京市  北京市
303  广东省  广州市
304  上海市  上海市
305  广东省  深圳市

### 多条件筛选

In [17]:
# AND：用 & 连接，每个条件要加括号
result = df[(df['城市级别'] == '二线') & (df['常住人口(万人)'] > 500)]
result

,省份,城市名称,城市级别,常住人口(万人),面积(km2),人均面积(km2/万人),火星纬度(GCJ02),火星经度(GCJ02)
10,黑龙江省,齐齐哈尔市,二线,524,42289,80.704198,47.3542,123.9180
33,云南省,曲靖市,二线,570,28942,50.775439,25.4850,103.7962
38,贵州省,遵义市,二线,689,30762,44.647315,27.7254,106.9276
42,江西省,赣州市,二线,913,39379,43.131435,25.8307,114.9356
44,云南省,昭通市,二线,537,23021,42.869646,27.3382,103.7175
46,湖南省,永州市,二线,527,22441,42.582543,26.4205,111.6134
49,贵州省,毕节市,二线,651,26853,41.248848,27.2841,105.2865
61,湖北省,襄阳市,二线,557,19662,35.299820,32.0097,112.1221
63,江西省,上饶市,二线,655,22791,34.795420,28.4547,117.9433
65,江西省,宜春市,二线,553,18669,33.759494,27.8043,114.3963
67,湖南省,常德市,二线,570,18190,31.912281,29.0315,111.6983
71,河南省,信阳市,二线,623,18908,30.349920,32.1285,114.0913
73,四川省,达州市,二线,556,16591,29.839928,31.2089,107.4677
78,湖北省,黄冈市,二线,615,17453,28.378862,30.4533,114.8726
80,河南省,南阳市,二线,967,26509,27.413650,33.0035,112.5292
82,湖北省,荆州市,二线,529,14067,26.591682,30.3342,112.2399
83,湖南省,岳阳市,二线,572,14897,26.043706,29.3578,113.1287
84,江苏省,盐城市,二线,671,16931,25.232489,33.3479,120.1633
85,陕西省,渭南市,二线,521,13134,25.209213,34.4998,109.5090
87,福建省,漳州市,二线,505,12607,24.964356,24.5137,117.6470
88,湖南省,邵阳市,二线,836,20829,24.915072,27.2418,111.4677
90,四川省,泸州市,二线,504,12232,24.269841,28.8717,105.4429
92,河北省,保定市,二线,923,22185,24.035753,38.8671,115.4643
95,河南省,洛阳市,二线,712,15230,21.390449,34.6184,112.4539
96,湖南省,衡阳市,二线,722,15309,21.203601,26.8932,112.5717
97,河南省,驻马店市,二线,715,15083,21.095105,32.9837,114.0224
99,广西壮族自治区,贵港市,二线,537,10602,19.743017,23.1115,109.5987
101,河北省,沧州市,二线,731,14304,19.567715,38.3044,116.8391
102,四川省,南充市,二线,639,12494,19.552426,30.8378,106.1098
106,山东省,烟台市,二线,710,13745,19.359155,37.5380,121.3914
108,广东省,惠州市,二线,604,11347,18.786424,23.1117,114.4162
109,山东省,德州市,二线,558,10356,18.559140,37.4351,116.3573
112,安徽省,宿州市,二线,533,9787,18.362101,33.6462,116.9642
113,广西壮族自治区,玉林市,二线,700,12838,18.340000,22.6298,110.1542
120,广东省,湛江市,二线,695,12106,17.418705,21.2707,110.3594
122,山东省,潍坊市,二线,930,16143,17.358065,36.7072,119.1618
123,广东省,茂名市,二线,663,11459,17.283560,21.6629,110.9254
124,河北省,邢台市,二线,729,12495,17.139918,37.0682,114.5048
126,安徽省,亳州市,二线,502,8374,16.681275,33.8444,115.7788
134,浙江省,绍兴市,二线,527,8274,15.700190,30.0302,120.5802
135,山东省,临沂市,二线,1101,17191,15.613987,35.1047,118.3564
136,浙江省,金华市,二线,705,10942,15.520567,29.0788,119.6476
138,河南省,商丘市,二线,732,10704,14.622951,34.4140,115.6503
139,山东省,聊城市,二线,600,8715,14.525000,36.4568,115.9853
140,河南省,安阳市,二线,510,7355,14.421569,36.0978,114.3924
141,河南省,新乡市,二线,574,8249,14.371080,35.3033,113.9268
142,浙江省,台州市,二线,661,9411,14.237519,28.6561,121.4285
144,山东省,泰安市,二线,549,7761,14.136612,36.1988,117.0880
145,山东省,菏泽市,二线,870,12239,14.067816,35.2333,115.4809
147,山东省,济宁市,二线,837,11186,13.364397,35.4154,116.5871
148,河南省,周口市,二线,896,11958,13.345982,33.6478,114.6490
150,江苏省,徐州市,二线,909,11765,12.942794,34.2044,117.2851
152,河北省,邯郸市,二线,954,12066,12.647799,36.6251,114.4897
154,浙江省,温州市,二线,957,11784,12.313480,28.0000,120.6722
157,安徽省,阜阳市,二线,820,9775,11.920732,32.8901,115.8197
160,河北省,廊坊市,二线,552,6429,11.646739,39.5376,116.6837
164,江苏省,南通市,二线,771,8001,10.377432,31.9801,120.8945
165,广东省,揭州市,二线,617,5266,8.534846,23.5479,116.3724
167,浙江省,嘉兴市,二线,547,3915,7.157221,30.7522,120.7559
169,广东省,汕头市,二线,554,2199,3.969314,23.3535,116.6820

In [18]:
# OR：用 | 连接
result = df[(df['城市级别'] == '一线') | (df['城市级别'] == '准一线')]
result

,省份,城市名称,城市级别,常住人口(万人),面积(km2),人均面积(km2/万人),火星纬度(GCJ02),火星经度(GCJ02)
302,北京市,北京市,一线,2189,16411,7.497031,39.9042,116.4074
303,广东省,广州市,一线,1882,7434,3.950053,23.1291,113.2644
304,上海市,上海市,一线,2489,6341,2.547609,31.2304,121.4737
305,广东省,深圳市,一线,1766,1997,1.130804,22.5431,114.0579
306,内蒙古自治区,包头市,准一线,271,27691,102.180812,40.6572,110.0037
307,黑龙江省,哈尔滨市,准一线,1000,53100,53.100000,45.8038,126.5349
308,内蒙古自治区,呼和浩特市,准一线,344,17186,49.959302,40.8415,111.7519
309,新疆维吾尔自治区,乌鲁木齐市,准一线,407,13788,33.877150,43.8256,87.6168
310,甘肃省,兰州市,准一线,436,13086,30.013761,36.0611,103.8343
311,重庆市,重庆市,准一线,3213,82403,25.646748,29.5630,106.5516
312,广西壮族自治区,南宁市,准一线,874,22112,25.299771,22.8170,108.3665
313,云南省,昆明市,准一线,846,21011,24.835697,25.0450,102.7093
314,吉林省,长春市,准一线,909,20565,22.623762,43.8171,125.3235
315,河北省,唐山市,准一线,760,13472,17.726316,39.6307,118.1803
316,辽宁省,大连市,准一线,745,12573,16.876510,38.9140,121.6147
317,福建省,福州市,准一线,829,11968,14.436671,26.0745,119.2965
318,辽宁省,沈阳市,准一线,907,12860,14.178611,41.8057,123.4315
319,河北省,石家庄市,准一线,1124,15848,14.099644,38.0428,114.5149
320,浙江省,杭州市,准一线,1237,16853,13.624091,30.2741,120.1551
321,贵州省,贵阳市,准一线,598,8034,13.434783,26.6470,106.6302
322,山西省,太原市,准一线,541,6909,12.770795,37.8706,112.5489
323,福建省,泉州市,准一线,878,11015,12.545558,24.8742,118.6757
324,安徽省,合肥市,准一线,963,11445,11.884735,31.8206,117.2272
325,江西省,南昌市,准一线,640,7402,11.565625,28.6820,115.8579
326,湖南省,长沙市,准一线,1042,11819,11.342610,28.2278,112.9388
327,山东省,青岛市,准一线,1007,11282,11.203575,36.0671,120.3826
328,山东省,济南市,准一线,941,10244,10.886291,36.6512,117.1201
329,浙江省,宁波市,准一线,969,9817,10.131063,29.8683,121.5440
330,天津市,天津市,准一线,1373,11917,8.679534,39.3434,117.3616
331,陕西省,西安市,准一线,1307,10752,8.226473,34.3416,108.9398
332,江苏省,常州市,准一线,534,4385,8.211610,31.7749,119.9740
333,江苏省,南京市,准一线,942,6587,6.992569,32.0603,118.7969
334,江苏省,南京市,准一线,942,6587,6.992569,32.0603,118.7969
335,四川省,成都市,准一线,2127,14335,6.739539,30.5728,104.0668
336,江苏省,苏州市,准一线,1285,8657,6.736965,31.2989,120.5853
337,湖北省,武汉市,准一线,1365,8569,6.277656,30.5928,114.3055
338,江苏省,无锡市,准一线,749,4628,6.178905,31.5691,120.2993
339,河南省,郑州市,准一线,1282,7567,5.902496,34.7466,113.6254
340,广东省,佛山市,准一线,961,3798,3.952133,23.0219,113.1219
341,福建省,厦门市,准一线,528,1701,3.221591,24.4797,118.0894
342,广东省,东莞市,准一线,1046,2462,2.353728,23.0207,113.7518

In [19]:
# NOT：用 ~ 取反
not_other = df[~(df['城市级别'] == '其他')]
not_other

,省份,城市名称,城市级别,常住人口(万人),面积(km2),人均面积(km2/万人),火星纬度(GCJ02),火星经度(GCJ02)
0,内蒙古自治区,呼伦贝尔市,二线,248,252777,1019.262097,49.2126,119.7654
1,内蒙古自治区,鄂尔多斯市,二线,215,86752,403.497674,39.6081,110.0235
2,内蒙古自治区,赤峰市,二线,430,90021,209.351163,42.2566,118.9220
3,内蒙古自治区,通辽市,二线,312,59535,190.817308,43.6529,122.2440
4,四川省,凉山彝族自治州,二线,484,60423,124.840909,27.8868,102.2674
...,...,...,...,...,...,...,...,...
338,江苏省,无锡市,准一线,749,4628,6.178905,31.5691,120.2993
339,河南省,郑州市,准一线,1282,7567,5.902496,34.7466,113.6254
340,广东省,佛山市,准一线,961,3798,3.952133,23.0219,113.1219
341,福建省,厦门市,准一线,528,1701,3.221591,24.4797,118.0894
342,广东省,东莞市,准一线,1046,2462,2.353728,23.0207,113.7518

### isin()：匹配多个值

In [20]:
# 筛选某几个省份
target_provinces = ['广东省', '浙江省', '江苏省']
south_cities = df[df['省份'].isin(target_provinces)]
south_cities

      省份  城市名称 城市级别  常住人口(万人)  面积(km2)  人均面积(km2/万人)  火星纬度(GCJ02)  火星经度(GCJ02)
18   广东省   韶关市   二线       281    18393     65.455516      24.8112     113.5975
31   广东省   清远市   二线       374    19196     51.326203      23.6820     113.0564
32   广东省   河源市   二线       307    15653     50.986971      23.7435     114.6977
47   广东省   梅州市   二线       374    15864     42.417112      24.2884     116.1226
58   广东省   肇庆市   二线       412    14891     36.143204      23.0469     112.4655
70   广东省   云浮市   二线       249     7785     31.265060      22.9155     112.0444
76   广东省   阳江市   二线       275     7956     28.930909      21.8579     111.9822
84   江苏省   盐城市   二线       671    16931     25.232489      33.3479     120.1633
98   广东省   江门市   二线       480     9505     19.802083      22.5789     113.0815
103  江苏省   淮安市   二线       492     9606     19.524390      33.5535     119.0213
108  广东省   惠州市   二线       604    11347     18.786424      23.1117     114.4162
119  浙江省   湖州市   二线       334     5818     17.419162      30.8702     120.0880
120  广东省   湛江市   二线       695    12106     17.418705      21.2707     110.3594
121  江苏省   宿迁市   二线       492     8555     17.388211      33.9626     118.2749
123  广东省   茂名市   二线       663    11459     17.283560      21.6629     110.9254
128  江苏省  连云港市   二线       453     7499     16.554084      34.5966     119.2219
133  广东省   汕尾市   二线       302     4865     16.109272      22.7864     115.3752
134  浙江省   绍兴市   二线       527     8274     15.700190      30.0302     120.5802
136  浙江省   金华市   二线       705    10942     15.520567      29.0788     119.6476
142  浙江省   台州市   二线       661     9411     14.237519      28.6561     121.4285
143  江苏省   扬州市   二线       463     6591     14.235421      32.3937     119.4127
150  江苏省   徐州市   二线       909    11765     12.942794      34.2044     117.2851
153  江苏省   泰州市   二线       466     5787     12.418455      32.4561     119.9232
154  浙江省   温州市   二线       957    11784     12.313480      28.0000     120.6722
156  江苏省   镇江市   二线       322     3840     11.925466      32.1884     119.4245
159  广东省   潮州市   二线       270     3146     11.651852      23.6567     116.6225
164  江苏省   南通市   二线       771     8001     10.377432      31.9801     120.8945
165  广东省   揭州市   二线       617     5266      8.534846      23.5479     116.3724
167  浙江省   嘉兴市   二线       547     3915      7.157221      30.7522     120.7559
168  广东省   中山市   二线       446     1784      4.000000      22.5176     113.3926
169  广东省   汕头市   二线       554     2199      3.969314      23.3535     116.6820
257  浙江省   丽水市   三线       253    17298     68.371542      28.4674     119.9230
278  浙江省   衢州市   三线       219     8841     40.369863      28.9356     118.8591
299  浙江省   舟山市   三线       116     1440     12.413793      29.9853     122.2069
303  广东省   广州市   一线      1882     7434      3.950053      23.1291     113.2644
305  广东省   深圳市   一线      1766     1997      1.130804      22.5431     114.0579
320  浙江省   杭州市  准一线      1237    16853     13.624091      30.2741     120.1551
329  浙江省   宁波市  准一线       969     9817     10.131063      29.8683     121.5440
332  江苏省   常州市  准一线       534     4385      8.211610      31.7749     119.9740
333  江苏省   南京市  准一线       942     6587      6.992569      32.0603     118.7969
334  江苏省   南京市  准一线       942     6587      6.992569      32.0603     118.7969
336  江苏省   苏州市  准一线      1285     8657      6.736965      31.2989     120.5853
338  江苏省   无锡市  准一线       749     4628      6.178905      31.5691     120.2993
340  广东省   佛山市  准一线       961     3798      3.952133      23.0219     113.1219
342  广东省   东莞市  准一线      1046     2462      2.353728      23.0207     113.7518

In [21]:
# 筛选非目标城市
other_cities = df[~df['省份'].isin(target_provinces)]
other_cities

,省份,城市名称,城市级别,常住人口(万人),面积(km2),人均面积(km2/万人),火星纬度(GCJ02),火星经度(GCJ02)
0,内蒙古自治区,呼伦贝尔市,二线,248,252777,1019.262097,49.2126,119.7654
1,内蒙古自治区,鄂尔多斯市,二线,215,86752,403.497674,39.6081,110.0235
2,内蒙古自治区,赤峰市,二线,430,90021,209.351163,42.2566,118.9220
3,内蒙古自治区,通辽市,二线,312,59535,190.817308,43.6529,122.2440
4,四川省,凉山彝族自治州,二线,484,60423,124.840909,27.8868,102.2674
...,...,...,...,...,...,...,...,...
331,陕西省,西安市,准一线,1307,10752,8.226473,34.3416,108.9398
335,四川省,成都市,准一线,2127,14335,6.739539,30.5728,104.0668
337,湖北省,武汉市,准一线,1365,8569,6.277656,30.5928,114.3055
339,河南省,郑州市,准一线,1282,7567,5.902496,34.7466,113.6254
341,福建省,厦门市,准一线,528,1701,3.221591,24.4797,118.0894

ERROR! Session/line number was not unique in database. History logging moved to new session 26

### between()：区间筛选

In [23]:
# 筛选人口在 100~500 万之间的城市
mid_cities = df[df['常住人口(万人)'].between(100, 500)]
mid_cities

,省份,城市名称,城市级别,常住人口(万人),面积(km2),人均面积(km2/万人),火星纬度(GCJ02),火星经度(GCJ02)
0,内蒙古自治区,呼伦贝尔市,二线,248,252777,1019.262097,49.2126,119.7654
1,内蒙古自治区,鄂尔多斯市,二线,215,86752,403.497674,39.6081,110.0235
2,内蒙古自治区,赤峰市,二线,430,90021,209.351163,42.2566,118.9220
3,内蒙古自治区,通辽市,二线,312,59535,190.817308,43.6529,122.2440
4,四川省,凉山彝族自治州,二线,484,60423,124.840909,27.8868,102.2674
...,...,...,...,...,...,...,...,...
300,河南省,漯河市,三线,271,2694,9.940959,33.5819,114.0161
306,内蒙古自治区,包头市,准一线,271,27691,102.180812,40.6572,110.0037
308,内蒙古自治区,呼和浩特市,准一线,344,17186,49.959302,40.8415,111.7519
309,新疆维吾尔自治区,乌鲁木齐市,准一线,407,13788,33.877150,43.8256,87.6168
310,甘肃省,兰州市,准一线,436,13086,30.013761,36.0611,103.8343

### str 系列：字符串匹配

In [24]:
# 城市名包含"市"
has_shi = df[df['城市名称'].str.contains('市')]
has_shi

,省份,城市名称,城市级别,常住人口(万人),面积(km2),人均面积(km2/万人),火星纬度(GCJ02),火星经度(GCJ02)
0,内蒙古自治区,呼伦贝尔市,二线,248,252777,1019.262097,49.2126,119.7654
1,内蒙古自治区,鄂尔多斯市,二线,215,86752,403.497674,39.6081,110.0235
2,内蒙古自治区,赤峰市,二线,430,90021,209.351163,42.2566,118.9220
3,内蒙古自治区,通辽市,二线,312,59535,190.817308,43.6529,122.2440
5,陕西省,榆林市,二线,370,42920,116.000000,38.2853,109.7341
...,...,...,...,...,...,...,...,...
338,江苏省,无锡市,准一线,749,4628,6.178905,31.5691,120.2993
339,河南省,郑州市,准一线,1282,7567,5.902496,34.7466,113.6254
340,广东省,佛山市,准一线,961,3798,3.952133,23.0219,113.1219
341,福建省,厦门市,准一线,528,1701,3.221591,24.4797,118.0894
342,广东省,东莞市,准一线,1046,2462,2.353728,23.0207,113.7518

In [25]:
# 省份以"省"结尾
provinces = df[df['省份'].str.endswith('省')]
provinces

,省份,城市名称,城市级别,常住人口(万人),面积(km2),人均面积(km2/万人),火星纬度(GCJ02),火星经度(GCJ02)
4,四川省,凉山彝族自治州,二线,484,60423,124.840909,27.8868,102.2674
5,陕西省,榆林市,二线,370,42920,116.000000,38.2853,109.7341
8,云南省,大理白族自治州,二线,349,29459,84.409742,25.6067,100.2677
9,贵州省,黔东南苗族侗族自治州,二线,362,30337,83.803867,26.5836,107.9777
10,黑龙江省,齐齐哈尔市,二线,524,42289,80.704198,47.3542,123.9180
...,...,...,...,...,...,...,...,...
338,江苏省,无锡市,准一线,749,4628,6.178905,31.5691,120.2993
339,河南省,郑州市,准一线,1282,7567,5.902496,34.7466,113.6254
340,广东省,佛山市,准一线,961,3798,3.952133,23.0219,113.1219
341,福建省,厦门市,准一线,528,1701,3.221591,24.4797,118.0894
342,广东省,东莞市,准一线,1046,2462,2.353728,23.0207,113.7518

In [26]:
# 忽略大小写
df[df['城市名称'].str.contains('Beijing', case=False)]

Empty DataFrame
Columns: [省份, 城市名称, 城市级别, 常住人口(万人), 面积(km2), 人均面积(km2/万人), 火星纬度(GCJ02), 火星经度(GCJ02)]
Index: []

---

## query()：写 SQL 风格的查询

对 SQL 熟悉的同学会喜欢这个：

In [30]:
# 等价于 df[(df['城市级别'] == '一线') & (df['常住人口(万人)'] > 500)]
result = df.query("城市级别 == '一线' and `常住人口(万人)` > 500")

# 用变量
min_pop = 500
result = df.query("`常住人口(万人)` > @min_pop")  # @ 引用变量
result

,省份,城市名称,城市级别,常住人口(万人),面积(km2),人均面积(km2/万人),火星纬度(GCJ02),火星经度(GCJ02)
10,黑龙江省,齐齐哈尔市,二线,524,42289,80.704198,47.3542,123.9180
33,云南省,曲靖市,二线,570,28942,50.775439,25.4850,103.7962
38,贵州省,遵义市,二线,689,30762,44.647315,27.7254,106.9276
42,江西省,赣州市,二线,913,39379,43.131435,25.8307,114.9356
44,云南省,昭通市,二线,537,23021,42.869646,27.3382,103.7175
...,...,...,...,...,...,...,...,...
338,江苏省,无锡市,准一线,749,4628,6.178905,31.5691,120.2993
339,河南省,郑州市,准一线,1282,7567,5.902496,34.7466,113.6254
340,广东省,佛山市,准一线,961,3798,3.952133,23.0219,113.1219
341,福建省,厦门市,准一线,528,1701,3.221591,24.4797,118.0894
342,广东省,东莞市,准一线,1046,2462,2.353728,23.0207,113.7518

---

## 实战：从全国城市数据里精准提取

In [33]:
import pandas as pd

df = pd.read_csv('全国城市数据.csv', encoding = 'gbk')

# 任务1：找出所有一线和准一线城市，按人口降序排列
top_cities = df[df['城市级别'].isin(['一线', '准一线'])]\
    .sort_values('常住人口(万人)', ascending=False)\
    [['省份', '城市名称', '城市级别', '常住人口(万人)']]\
    .reset_index(drop=True)
print("一线+准一线城市（按人口降序）:")
print(top_cities)

# 任务2：找出面积最大的10个城市
largest = df.nlargest(10, '面积(km2)')[['城市名称', '省份', '面积(km2)']]
print("\n面积最大的10个城市:")
print(largest)

# 任务3：广东省所有城市
guangdong = df[df['省份'] == '广东省'][['城市名称', '城市级别', '常住人口(万人)']]
print(f"\n广东省城市（共{len(guangdong)}个）:")
print(guangdong)

一线+准一线城市（按人口降序）:
          省份   城市名称 城市级别  常住人口(万人)
0        重庆市    重庆市  准一线      3213
1        上海市    上海市   一线      2489
2        北京市    北京市   一线      2189
3        四川省    成都市  准一线      2127
4        广东省    广州市   一线      1882
5        广东省    深圳市   一线      1766
6        天津市    天津市  准一线      1373
7        湖北省    武汉市  准一线      1365
8        陕西省    西安市  准一线      1307
9        江苏省    苏州市  准一线      1285
10       河南省    郑州市  准一线      1282
11       浙江省    杭州市  准一线      1237
12       河北省   石家庄市  准一线      1124
13       广东省    东莞市  准一线      1046
14       湖南省    长沙市  准一线      1042
15       山东省    青岛市  准一线      1007
16      黑龙江省   哈尔滨市  准一线      1000
17       浙江省    宁波市  准一线       969
18       安徽省    合肥市  准一线       963
19       广东省    佛山市  准一线       961
20       江苏省    南京市  准一线       942
21       江苏省    南京市  准一线       942
22       山东省    济南市  准一线       941
23       吉林省    长春市  准一线       909
24       辽宁省    沈阳市  准一线       907
25       福建省    泉州市  准一线       878
26   广西壮族自治区    南宁市  准一线       874
27       云南省    昆明市  准一线       846
28       福建省    福州市  准一线       829
29       河北省    唐山市  准一线       760
30       江苏省    无锡市  准一线       749
31       辽宁省    大连市  准一线       745
32       江西省    南昌市  准一线       640
33       贵州省    贵阳市  准一线       598
34       山西省    太原市  准一线       541
35       江苏省    常州市  准一线       534
36       福建省    厦门市  准一线       528
37       甘肃省    兰州市  准一线       436
38  新疆维吾尔自治区  乌鲁木齐市  准一线       407
39    内蒙古自治区  呼和浩特市  准一线       344
40    内蒙古自治区    包头市  准一线       271

面积最大的10个城市:
           城市名称        省份  面积(km2)
177   巴音郭楞蒙古自治州  新疆维吾尔自治区   471526
173         那曲市     西藏自治区   392000
175  海西蒙古族藏族自治州       青海省   308457
171        阿里地区     西藏自治区   304683
172        阿拉善盟    内蒙古自治区   270000
174     玉树藏族自治州       青海省   267864
0         呼伦贝尔市    内蒙古自治区   252777
193        和田地区  新疆维吾尔自治区   248800
182       锡林郭勒盟    内蒙古自治区   202580
179        日喀则市     西藏自治区   182000

广东省城市（共20个）:
    城市名称 城市级别  常住人口(万人)
18   韶关市   二线       281
31   清远市   二线       374
32   河源市   二线       307
47   梅州市   二线       374
58   肇庆市   二线       412
70   云浮市   二线       249
76   阳江市   二线       275
98   江门市   二线       480
108  惠州市   二线       604
120  湛江市   二线       695
123  茂名市   二线       663
133  汕尾市   二线       302
159  潮州市   二线       270
165  揭州市   二线       617
168  中山市   二线       446
169  汕头市   二线       554
303  广州市   一线      1882
305  深圳市   一线      1766
340  佛山市  准一线       961
342  东莞市  准一线      1046

---

## 选列的简洁写法汇总

In [ ]:
# 选单列
df['列名']        # 返回 Series
df[['列名']]      # 返回 DataFrame（双括号！）

# 选多列
df[['列1', '列2', '列3']]

# 按类型选列
df.select_dtypes(include='number')    # 所有数值列
df.select_dtypes(include='object')    # 所有字符串列

# 按列名过滤（列名包含某字符串）
df.filter(like='人口')   # 选出列名含"人口"的所有列
df.filter(regex='^火星')  # 列名以"火星"开头的列

---

## 本篇小结

| 方法 | 用途 | 特点 |
|------|------|------|
| `iloc[行, 列]` | 按位置取 | 整数，切片不含末端 |
| `loc[行, 列]` | 按标签取 | 列名/索引，切片含末端 |
| `df[条件]` | 条件筛选 | 布尔索引 |
| `isin([...])` | 多值匹配 | 等价于 SQL IN |
| `between(a, b)` | 区间筛选 | 闭区间 |
| `str.contains()` | 字符串筛选 | 支持正则 |
| `query()` | SQL 风格查询 | 代码更简洁 |

---

## 课后练习

用 `全国城市数据.csv`，写代码完成：

1. 筛选出"三线城市"中人口超过 300 万的城市
2. 找出经度在 120~125 之间的城市（东部沿海区域）
3. 筛选出省份名不含"省"也不含"市"的行政区（自治区/直辖市等）

In [34]:
# 筛选出"三线城市"中人口超过 300 万的城市
df.query("城市级别 == '三线' and `常住人口(万人)` > 300")

,省份,城市名称,城市级别,常住人口(万人),面积(km2),人均面积(km2/万人),火星纬度(GCJ02),火星经度(GCJ02)
204,新疆维吾尔自治区,喀什地区,三线,451,162000,359.201774,39.4674,75.9889
233,河北省,承德市,三线,365,39519,108.271233,40.9516,117.9633
245,河北省,张家口市,三线,431,36860,85.522042,40.8244,114.8854
246,云南省,文山壮族苗族自治州,三线,369,31456,85.246612,23.3685,104.2477
256,黑龙江省,绥化市,三线,501,34873,69.606786,46.6371,126.9887
259,辽宁省,朝阳市,三线,302,19736,65.350993,41.5768,120.4510
262,湖北省,恩施土家族苗族自治州,三线,387,24060,62.170543,30.2955,109.4869
275,吉林省,四平市,三线,316,14080,44.556962,43.1665,124.3708
279,四川省,巴中市,三线,308,12292,39.909091,31.8670,106.7474
294,河北省,衡水市,三线,428,8815,20.595794,37.7393,115.6714

In [36]:
# 找出经度在 120~125 之间的城市（东部沿海区域）
df[df['火星经度(GCJ02)'].between(120, 125)]

,省份,城市名称,城市级别,常住人口(万人),面积(km2),人均面积(km2/万人),火星纬度(GCJ02),火星经度(GCJ02)
3,内蒙古自治区,通辽市,二线,312,59535,190.817308,43.6529,122.2440
10,黑龙江省,齐齐哈尔市,二线,524,42289,80.704198,47.3542,123.9180
19,辽宁省,丹东市,二线,234,15222,65.051282,40.1291,124.3836
24,辽宁省,本溪市,二线,147,8438,57.401361,41.2867,123.7655
26,辽宁省,抚顺市,二线,199,11272,56.643216,41.8795,123.9574
62,辽宁省,锦州市,二线,287,10093,35.167247,41.1192,121.1269
74,辽宁省,盘锦市,二线,139,4065,29.244604,41.1218,122.0708
81,辽宁省,鞍山市,二线,343,9252,26.973761,41.1082,122.9963
84,江苏省,盐城市,二线,671,16931,25.232489,33.3479,120.1633
93,辽宁省,营口市,二线,229,5402,23.589520,40.6680,122.2351
100,山东省,威海市,二线,294,5799,19.724490,37.5130,122.1213
106,山东省,烟台市,二线,710,13745,19.359155,37.5380,121.3914
119,浙江省,湖州市,二线,334,5818,17.419162,30.8702,120.0880
134,浙江省,绍兴市,二线,527,8274,15.700190,30.0302,120.5802
142,浙江省,台州市,二线,661,9411,14.237519,28.6561,121.4285
154,浙江省,温州市,二线,957,11784,12.313480,28.0000,120.6722
164,江苏省,南通市,二线,771,8001,10.377432,31.9801,120.8945
167,浙江省,嘉兴市,二线,547,3915,7.157221,30.7522,120.7559
185,黑龙江省,大兴安岭地区,三线,51,83421,1635.705882,51.9937,124.1208
205,内蒙古自治区,兴安盟,三线,161,55016,341.714286,46.0765,122.0653
228,吉林省,白城市,三线,196,25700,131.122449,45.6175,122.8419
249,吉林省,松原市,三线,278,22042,79.287770,45.1409,124.8252
259,辽宁省,朝阳市,三线,302,19736,65.350993,41.5768,120.4510
265,辽宁省,阜新市,三线,171,10355,60.555556,42.0217,121.6486
271,辽宁省,铁岭市,三线,254,12982,51.110236,42.2978,123.8444
275,吉林省,四平市,三线,316,14080,44.556962,43.1665,124.3708
280,辽宁省,葫芦岛市,三线,261,10415,39.904215,40.7107,120.8370
292,辽宁省,辽阳市,三线,181,4743,26.204420,41.2736,123.2310
299,浙江省,舟山市,三线,116,1440,12.413793,29.9853,122.2069
304,上海市,上海市,一线,2489,6341,2.547609,31.2304,121.4737
316,辽宁省,大连市,准一线,745,12573,16.876510,38.9140,121.6147
318,辽宁省,沈阳市,准一线,907,12860,14.178611,41.8057,123.4315
320,浙江省,杭州市,准一线,1237,16853,13.624091,30.2741,120.1551
327,山东省,青岛市,准一线,1007,11282,11.203575,36.0671,120.3826
329,浙江省,宁波市,准一线,969,9817,10.131063,29.8683,121.5440
336,江苏省,苏州市,准一线,1285,8657,6.736965,31.2989,120.5853
338,江苏省,无锡市,准一线,749,4628,6.178905,31.5691,120.2993

In [39]:
# 筛选出省份名不含"省"也不含"市"的行政区（自治区/直辖市等）
df[~(df['省份'].str.endswith(('省','市')))]

,省份,城市名称,城市级别,常住人口(万人),面积(km2),人均面积(km2/万人),火星纬度(GCJ02),火星经度(GCJ02)
0,内蒙古自治区,呼伦贝尔市,二线,248,252777,1019.262097,49.2126,119.7654
1,内蒙古自治区,鄂尔多斯市,二线,215,86752,403.497674,39.6081,110.0235
2,内蒙古自治区,赤峰市,二线,430,90021,209.351163,42.2566,118.9220
3,内蒙古自治区,通辽市,二线,312,59535,190.817308,43.6529,122.2440
6,广西壮族自治区,百色市,二线,350,36300,103.714286,23.9021,106.6183
7,广西壮族自治区,河池市,二线,335,33476,99.928358,24.6926,108.0857
27,广西壮族自治区,桂林市,二线,493,27809,56.407708,25.2736,110.2996
39,广西壮族自治区,柳州市,二线,422,18596,44.066351,24.3264,109.4281
41,广西壮族自治区,梧州市,二线,290,12597,43.437931,23.4766,111.2905
64,广西壮族自治区,钦州市,二线,318,10897,34.267296,21.9813,108.6538
68,宁夏回族自治区,银川市,二线,286,9026,31.559441,38.4874,106.2309
99,广西壮族自治区,贵港市,二线,537,10602,19.743017,23.1115,109.5987
113,广西壮族自治区,玉林市,二线,700,12838,18.340000,22.6298,110.1542
116,广西壮族自治区,北海市,二线,185,3337,18.037838,21.4812,109.1196
171,西藏自治区,阿里地区,三线,12,304683,25390.250000,32.5042,80.1095
172,内蒙古自治区,阿拉善盟,三线,24,270000,11250.000000,38.8514,105.7268
173,西藏自治区,那曲市,三线,50,392000,7840.000000,31.4761,92.0516
176,西藏自治区,林芝市,三线,24,117000,4875.000000,29.6482,94.3622
177,新疆维吾尔自治区,巴音郭楞蒙古自治州,三线,127,471526,3712.803150,41.7680,86.1468
179,西藏自治区,日喀则市,三线,70,182000,2600.000000,29.2676,88.8854
180,新疆维吾尔自治区,哈密市,三线,62,138900,2240.322581,42.8187,93.5152
181,西藏自治区,山南市,三线,37,80652,2179.783784,29.2352,91.7726
182,内蒙古自治区,锡林郭勒盟,三线,104,202580,1947.884615,43.9432,116.0714
183,新疆维吾尔自治区,图木舒克市,三线,13,24400,1876.923077,39.8681,79.0776
184,新疆维吾尔自治区,阿勒泰地区,三线,66,117847,1785.560606,47.8436,88.1399
187,西藏自治区,昌都市,三线,78,109870,1408.589744,31.1382,97.1719
190,新疆维吾尔自治区,克孜勒苏柯尔克孜自治州,三线,64,72496,1132.750000,39.7143,76.1680
191,新疆维吾尔自治区,吐鲁番市,三线,64,69713,1089.265625,42.9474,89.1893
192,新疆维吾尔自治区,塔城地区,三线,96,101099,1053.114583,46.7469,82.9765
193,新疆维吾尔自治区,和田地区,三线,247,248800,1007.287449,37.1144,79.9300
197,新疆维吾尔自治区,昌吉回族自治州,三线,117,73660,629.572650,44.0132,87.3080
200,新疆维吾尔自治区,博尔塔拉蒙古自治州,三线,48,24460,509.583333,44.9060,82.0523
201,新疆维吾尔自治区,阿克苏地区,三线,262,131549,502.095420,41.1681,80.2636
203,内蒙古自治区,巴彦淖尔市,三线,155,64341,415.103226,40.7568,107.3954
204,新疆维吾尔自治区,喀什地区,三线,451,162000,359.201774,39.4674,75.9889
205,内蒙古自治区,兴安盟,三线,161,55016,341.714286,46.0765,122.0653
207,西藏自治区,拉萨市,三线,87,29518,339.287356,29.6625,91.1322
208,内蒙古自治区,乌兰察布市,三线,172,54491,316.808139,40.9942,113.1148
211,新疆维吾尔自治区,阿拉尔市,三线,68,16900,248.529412,40.5465,81.2804
214,新疆维吾尔自治区,伊犁哈萨克自治州,三线,277,56400,203.610108,43.9220,81.3243
215,新疆维吾尔自治区,克拉玛依市,三线,47,9548,203.148936,45.5797,84.8893
220,宁夏回族自治区,中卫市,三线,108,17441,161.490741,37.5208,105.1898
231,宁夏回族自治区,吴忠市,三线,143,16745,117.097902,37.9924,106.2020
240,宁夏回族自治区,固原市,三线,152,13639,89.730263,36.0160,106.2426
244,广西壮族自治区,崇左市,三线,201,17332,86.228856,22.3768,107.3641
251,宁夏回族自治区,石嘴山市,三线,71,5310,74.788732,38.9843,106.3776
258,广西壮族自治区,防城港市,三线,93,6181,66.462366,21.6872,108.3634
260,广西壮族自治区,来宾市,三线,210,13411,63.861905,23.7518,109.2218
266,广西壮族自治区,贺州市,三线,200,11855,59.275000,24.4077,111.5665
281,新疆维吾尔自治区,五家渠市,三线,21,791,37.666667,44.1671,87.5263
286,内蒙古自治区,乌海市,三线,56,1754,31.321429,39.6551,106.8214
301,新疆维吾尔自治区,石河子市,三线,66,476,7.212121,44.3064,86.0372
306,内蒙古自治区,包头市,准一线,271,27691,102.180812,40.6572,110.0037
308,内蒙古自治区,呼和浩特市,准一线,344,17186,49.959302,40.8415,111.7519
309,新疆维吾尔自治区,乌鲁木齐市,准一线,407,13788,33.877150,43.8256,87.6168
312,广西壮族自治区,南宁市,准一线,874,22112,25.299771,22.8170,108.3665

评论区见 👀

本篇完整代码包括练习题解答都已经上传至 GitHub 仓库，欢迎 Clone。

---

## 下期预告

> **第 11 篇：缺失值处理 — 5 种策略全解析**
>
> 真实数据永远有缺失值，怎么删、怎么填、什么时候用什么策略——下篇用一份"脏数据集"把所有情况都走一遍。

---

👇 点「在看」，推给想搞定数据筛选的人  
💬 评论区说说你 loc 和 iloc 用哪个更顺手  
⭐ 关注公众号，跟萧何迷妹一起进阶

---

*「数据分析从入门到精通」系列 · 第 10 篇*  
*上一篇：[第 9 篇：数据查看与描述性统计]*  
*下一篇：第 11 篇：缺失值处理 — 5 种策略全解析*